# Generated by Django 5.1.7 on 2025-05-21 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_configuracionparental'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComponenteAvatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('imagen', models.ImageField(upload_to='avatar/componentes/')),
                ('tipo', models.CharField(choices=[('pelo', 'Pelo'), ('ojos', 'Ojos'), ('ropa', 'Ropa'), ('accesorio', 'Accesorio')], max_length=50)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('precio', models.IntegerField(default=0)),
                ('desbloqueado', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['tipo', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vista_previa', models.ImageField(blank=True, null=True, upload_to='avatar/previews/')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('perfil', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='avatar_personalizado', to='users.perfilinfantil')),
                ('accesorio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avatares_accesorio', to='avatar.componenteavatar')),
                ('ojos', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avatares_ojos', to='avatar.componenteavatar')),
                ('pelo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avatares_pelo', to='avatar.componenteavatar')),
                ('ropa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avatares_ropa', to='avatar.componenteavatar')),
            ],
        ),
        migrations.CreateModel(
            name='Recompensa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('imagen', models.ImageField(upload_to='avatar/recompensas/')),
                ('puntos', models.IntegerField(default=0)),
                ('tipo', models.CharField(choices=[('logro', 'Logro'), ('actividad', 'Actividad'), ('diario', 'Diario'), ('especial', 'Especial')], max_length=50)),
                ('componente_desbloquea', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recompensas_desbloqueo', to='avatar.componenteavatar')),
            ],
        ),
        migrations.CreateModel(
            name='RecompensaPerfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_obtencion', models.DateTimeField(auto_now_add=True)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recompensas', to='users.perfilinfantil')),
                ('recompensa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perfiles', to='avatar.recompensa')),
            ],
            options={
                'unique_together': {('perfil', 'recompensa')},
            },
        ),
    ]
