# Generated by Django 4.2.21 on 2025-05-31 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0004_perfilinfantil_user_infantil'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text="Código interno único del logro (ej. 'snake_10_manzanas', 'cuento1_leido', etc.)", max_length=50, unique=True)),
                ('titulo', models.CharField(help_text="Título legible para el usuario (ej. '¡Maestro de la Serpiente!').", max_length=100)),
                ('descripcion', models.TextField(help_text='Texto explicativo de cómo se desbloquea este logro.')),
                ('juego_id', models.PositiveIntegerField(blank=True, help_text='ID del juego (tabla juegos_juego) al que aplica este logro, si corresponde.', null=True)),
                ('cuento_id', models.PositiveIntegerField(blank=True, help_text='ID del cuento (tabla cuentos_cuento) al que aplica este logro, si corresponde.', null=True)),
                ('umbral', models.PositiveIntegerField(default=0, help_text='Valor numérico mínimo para desbloquear, dependiendo de si es juego o cuento.')),
                ('activo', models.BooleanField(default=True, help_text='Si está True, aparece en la lista de logros disponibles; si False, no se muestra.')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PerfilLogro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_desbloqueado', models.DateTimeField(auto_now_add=True)),
                ('logro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perfiles', to='logros.logro')),
                ('perfil_infantil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logros_desbloqueados', to='users.perfilinfantil')),
            ],
            options={
                'unique_together': {('perfil_infantil', 'logro')},
            },
        ),
    ]
