version: '3.9'

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: db_lingokidsworld
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./database/db_lingokidsworld.sql:/docker-entrypoint-initdb.d/db_lingokidsworld.sql
    command: --default-authentication-plugin=mysql_native_password

  backend:
    build: ./backend
    command: sh -c "python manage.py migrate && python manage.py collectstatic --noinput && gunicorn backend.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - ./backend:/app
      - static_data:/app/static
      - media_data:/app/media
    environment:
      - DJANGO_SETTINGS_MODULE=backend.settings
      - MYSQL_DATABASE=db_lingokidsworld
      - MYSQL_USER=root
      - MYSQL_PASSWORD=admin
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
    depends_on:
      - db
    expose:
      - "8000"
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  db_data:
  static_data:
  media_data:
