# Generated by Django 5.1.7 on 2025-04-03 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cuento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idioma', models.CharField(max_length=50)),
                ('titulo', models.CharField(max_length=200)),
                ('contenido', models.JSONField(help_text='Estructura del cuento: escenas, diálogos, elecciones, etc.')),
                ('personalizable', models.BooleanField(default=False)),
            ],
        ),
    ]
