# Generated by Django 4.2.21 on 2025-05-25 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuento',
            name='categoria',
            field=models.CharField(default='General', max_length=100),
        ),
        migrations.AddField(
            model_name='cuento',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='cuentos/'),
        ),
    ]
