# Generated by Django 4.2.21 on 2025-05-25 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentos', '0002_cuento_categoria_cuento_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuento',
            name='imagen',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
