# Generated by Django 5.1.7 on 2025-05-21 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_configuracionparental'),
    ]

    operations = [
        migrations.CreateModel(
            name='Juego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('contenido', models.JSONField(help_text='Estructura del juego: niveles, preguntas, respuestas, etc.')),
                ('idioma', models.CharField(choices=[('es', 'Español'), ('en', 'English')], max_length=2)),
                ('imagen', models.ImageField(upload_to='juegos/')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoJuego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('icono', models.ImageField(blank=True, null=True, upload_to='tipos_juegos/')),
                ('nivel_dificultad', models.IntegerField(choices=[(1, 'Fácil'), (2, 'Medio'), (3, 'Difícil')])),
                ('edad_minima', models.IntegerField()),
                ('edad_maxima', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='EstadisticaJuego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_jugadores', models.IntegerField(default=0)),
                ('promedio_puntuacion', models.FloatField(default=0.0)),
                ('tiempo_promedio', models.IntegerField(default=0)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('juego', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estadisticas', to='juegos.juego')),
            ],
        ),
        migrations.AddField(
            model_name='juego',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='juegos', to='juegos.tipojuego'),
        ),
        migrations.CreateModel(
            name='ProgresoJuego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntuacion', models.PositiveIntegerField(default=0)),
                ('nivel_completado', models.PositiveIntegerField(default=0)),
                ('tiempo_jugado', models.PositiveIntegerField(default=0)),
                ('fecha_ultima_partida', models.DateTimeField(auto_now=True)),
                ('completado', models.BooleanField(default=False)),
                ('juego', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresos', to='juegos.juego')),
                ('perfil_infantil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresos_juegos', to='users.perfilinfantil')),
            ],
            options={
                'unique_together': {('perfil_infantil', 'juego')},
            },
        ),
    ]
