# Generated by Django 4.2.21 on 2025-05-31 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juegos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juego',
            name='contenido',
            field=models.JSONField(blank=True, default=dict, help_text='JSON con la lógica interna del juego (niveles, palabras, etc.)'),
        ),
        migrations.AlterField(
            model_name='juego',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='juegos/'),
        ),
        migrations.DeleteModel(
            name='ProgresoJuego',
        ),
    ]
