# Generated by Django 4.2.21 on 2025-05-31 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('juegos', '0002_alter_juego_contenido_alter_juego_imagen_and_more'),
        ('users', '0003_user_parent'),
        ('cuentos', '0003_alter_cuento_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgresoGeneral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiempo_total', models.IntegerField(default=0, help_text='Tiempo total en la app, en segundos')),
                ('tiempo_juegos', models.IntegerField(default=0, help_text='Tiempo dedicado a juegos, en segundos')),
                ('tiempo_cuentos', models.IntegerField(default=0, help_text='Tiempo dedicado a cuentos, en segundos')),
                ('actualizado', models.DateTimeField(auto_now=True, help_text='Última vez que se actualizó este registro')),
                ('perfil_infantil', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='progreso_general', to='users.perfilinfantil')),
            ],
        ),
        migrations.CreateModel(
            name='ProgresoJuego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiempo_jugado', models.IntegerField(default=0, help_text='Tiempo total jugado en este juego, en segundos')),
                ('estadisticas', models.JSONField(blank=True, default=dict, help_text="JSON con llaves específicas del juego, ej: {'rondas_completas': 3, 'ptje_max': 1500}")),
                ('actualizado', models.DateTimeField(auto_now=True, help_text='Última vez que se modificó')),
                ('juego', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresos', to='juegos.juego')),
                ('perfil_infantil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresos_juegos', to='users.perfilinfantil')),
            ],
            options={
                'verbose_name': 'Progreso de Juego',
                'verbose_name_plural': 'Progresos de Juegos',
                'unique_together': {('perfil_infantil', 'juego')},
            },
        ),
        migrations.CreateModel(
            name='ProgresoCuento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiempo_leido', models.IntegerField(default=0, help_text='Cuántos segundos lleva leyendo este cuento')),
                ('pag_actual', models.IntegerField(default=0, help_text='Página actual en la que va el niño')),
                ('completado', models.BooleanField(default=False, help_text='Si el niño completó el cuento o no')),
                ('actualizado', models.DateTimeField(auto_now=True, help_text='Última vez que se modificó')),
                ('cuento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresos_cuentos', to='cuentos.cuento')),
                ('perfil_infantil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresos_cuentos', to='users.perfilinfantil')),
            ],
            options={
                'verbose_name': 'Progreso de Cuento',
                'verbose_name_plural': 'Progresos de Cuentos',
                'unique_together': {('perfil_infantil', 'cuento')},
            },
        ),
    ]
