# Generated by Django 5.1.7 on 2025-04-03 17:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilInfantil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('edad', models.PositiveIntegerField()),
                ('avatar', models.CharField(default='avatar_default_1', max_length=100)),
                ('usuario_padre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perfiles_infantiles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
