# Generated by Django 4.2.21 on 2025-05-31 21:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilinfantil',
            name='user_infantil',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='perfil_infantil', to=settings.AUTH_USER_MODEL),
        ),
    ]
